version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=esp8266_mysql
      - MYSQL_ROOT_PASSWORD=esp8266_mysql_secret
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules

  web:
    container_name: web
    build:
      context: ./web
    ports:
      - '8180:80'
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules

# Names our volume
volumes:
  db:
